AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  LuckyPets Customer Notification System
  Event-driven serverless notifications for logistics

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs18.x
    Environment:
      Variables:
        STAGE: !Ref Stage

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
    Description: Deployment stage

Resources:
  # Lambda Function
  LuckyPetsNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "luckypets-notifications-${Stage}"
      CodeUri: ./
      Handler: index.handler
      Description: "Processes LuckyPets logistics events and sends customer notifications"

      # API Gateway Integration
      Events:
        NotificationApi:
          Type: Api
          Properties:
            Path: /webhook
            Method: post

      # IAM Permissions
      Policies:
        - SESCrudPolicy:
            IdentityName: "luckypets.com"
        - SNSPublishMessagePolicy:
            TopicName: "*"
        - CloudWatchPutMetricPolicy: {}
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: "*"

  # CloudWatch Log Group
  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/luckypets-notifications-${Stage}"
      RetentionInDays: 14

Outputs:
  LambdaFunctionArn:
    Description: "ARN of the Lambda function"
    Value: !GetAtt LuckyPetsNotificationFunction.Arn
    Export:
      Name: !Sub "${Stage}-luckypets-notification-function-arn"

  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook"
    Export:
      Name: !Sub "${Stage}-luckypets-api-endpoint"

  LambdaFunctionName:
    Description: "Lambda function name"
    Value: !Ref LuckyPetsNotificationFunction