server:
  port: 8085

spring:
  application:
    name: notificationView-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: notificationView-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.luckypets.logistics.shared.events"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.luckypets.logistics.shared.events.ShipmentCreatedEvent
        session.timeout.ms: 30000
        heartbeat.interval.ms: 10000
        max.poll.records: 500
        max.poll.interval.ms: 300000

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        acks: all
        retries: 3
        batch.size: 16384
        linger.ms: 5
        buffer.memory: 33554432
        enable.idempotence: true

    listener:
      ack-mode: manual_immediate

    topic:
      shipment-created: shipment-created
      shipment-scanned: shipment-scanned
      shipment-delivered: shipment-delivered
      notification-sent: notification-sent

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.luckypets.logistics: INFO
    org.springframework.kafka: INFO
    org.apache.kafka: WARN

---

spring:
  config:
    activate:
      on-profile: docker

  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    root: INFO
    com.luckypets.logistics: DEBUG