spring:
  kafka:
    topic:
      notification-sent: notification-sent-integration-test
    consumer:
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
      auto-offset-reset: earliest
      enable-auto-commit: false
      group-id: notification-integration-test
    producer:
      properties:
        spring.json.add.type.headers: true
      acks: 1
    listener:
      auto-startup: true
      ack-mode: manual_immediate

# Logging for integration tests
logging:
  level:
    com.luckypets.logistics: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    org.testcontainers: INFO
    root: INFO

# Server configuration for web tests
server:
  port: 0  # Random port for integration tests