server:
  port: 8085

spring:
  application:
    name: notification-view-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: notification-view-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      # Remove complex properties - let the custom ConsumerConfig handle this

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true

    listener:
      ack-mode: manual_immediate
      auto-startup: true

    # Topic configuration - these are used by the listeners
    topic:
      shipment-created: shipment-created
      shipment-scanned: shipment-scanned
      shipment-delivered: shipment-delivered
      notification-sent: notification-sent

  retry:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Enhanced logging for debugging
logging:
  level:
    com.luckypets.logistics.notificationviewservice: DEBUG
    org.springframework.kafka: INFO
    org.apache.kafka: WARN
    # Specific debugging for listeners
    com.luckypets.logistics.notificationviewservice.listener: DEBUG
    com.luckypets.logistics.notificationviewservice.service: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

---

spring:
  config:
    activate:
      on-profile: docker

  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    root: INFO
    com.luckypets.logistics.notificationviewservice: DEBUG

---

spring:
  config:
    activate:
      on-profile: test

  kafka:
    bootstrap-servers: ${spring.embedded.kafka.brokers}

logging:
  level:
    com.luckypets.logistics.notificationviewservice: DEBUG
    org.springframework.kafka: DEBUG

    luckypets:
      serverless:
        enabled: true
        webhook:
          url: https://bpq9p3cax1.execute-api.eu-central-1.amazonaws.com/Prod/webhook
