server:
  port: 8084

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    streams:
      application-id: analytics-service
      default-key-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      default-value-serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      properties:
        reconnect.backoff.ms: 1000
        reconnect.backoff.max.ms: 10000
        retry.backoff.ms: 1000
        request.timeout.ms: 30000
        connections.max.idle.ms: 600000

  output:
    ansi:
      enabled: ALWAYS

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka:9092
