

server:
  port: 8084

spring:
  application:
    name: analytics-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    streams:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      application-id: analytics-service-v1
      properties:
        processing.guarantee: exactly_once_v2
        commit.interval.ms: 10000
        cache.max.bytes.buffering: 10485760
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.springframework.kafka.support.serializer.JsonSerde
        default.timestamp.extractor: com.luckypets.logistics.analyticservice.timestamp.DeliveredAtTimestampExtractor

    consumer:
      group-id: analytics-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.luckypets.logistics.shared.events
        spring.json.add.type.headers: true

# Kafka Topics
kafka:
  topic:
    delivered: shipment-delivered
    delivery-analytics: delivery-analytics

  streams:
    state-store-name: delivery-count-store
    window:
      size-minutes: 60  # 1 Stunde Fenster
      grace-period-minutes: 5  # 5 Minuten Grace Period
    window-size-hours: 1
    max-results: 1000
    state-store:
      retention-days: 7

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,kafka-streams
  endpoint:
    health:
      show-details: always
    kafka-streams:
      cache:
        time-to-live: 10s

# Logging
logging:
  level:
    com.luckypets.logistics: INFO
    org.apache.kafka.streams: INFO
    org.springframework.kafka: INFO
    root: INFO

# App Configuration
app:
  default-timezone: Europe/Berlin

---
# Docker Profile
spring:
  config:
    activate:
      on-profile: docker

  kafka:
    bootstrap-servers: kafka:9092
    streams:
      bootstrap-servers: kafka:9092

logging:
  level:
    root: INFO