CREATE DATABASE shipment;
CREATE DATABASE scan;
CREATE DATABASE delivery;
CREATE DATABASE notification;


CREATE USER shipment WITH PASSWORD 'shipment_pw';
CREATE USER scan WITH PASSWORD 'scan_pw';
CREATE USER delivery WITH PASSWORD 'delivery_pw';
CREATE USER notification WITH PASSWORD 'notification_pw';

GRANT ALL PRIVILEGES ON DATABASE shipment TO shipment;
GRANT ALL PRIVILEGES ON DATABASE scan TO scan;
GRANT ALL PRIVILEGES ON DATABASE delivery TO delivery;
GRANT ALL PRIVILEGES ON DATABASE notification TO notification;
